/*
 * memote
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package viewmodel

import (
	"time"
)

type StayedLocationViewModel struct {
	Name string `json:"name"`

	Latitude float64 `json:"latitude"`

	Longitude float64 `json:"longitude"`

	Pictures []string `json:"pictures"`

	StartTime time.Time `json:"startTime"`

	EndTime time.Time `json:"endTime"`

	Message string `json:"message"`

	EmotionType int32 `json:"emotionType"`

	EmotionLevel int32 `json:"emotionLevel"`
}
