openapi: 3.0.0
info:
  title: memote
  version: 1.0.0
servers:
- url: https://memote.an.r.appspot.com/
security:
- bearerAuth: []
paths:
  /records:
    post:
      operationId: postRecords
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordViewModel'
        description: the content of the record
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessViewModel'
          description: Successfully posted record
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorViewModel'
          description: RequestBody is invalid
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorViewModel'
          description: Token missed or invalid
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorViewModel'
          description: Internal error
      summary: post records
      tags:
      - records
components:
  schemas:
    RecordViewModel:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        locations:
        - time: 2000-01-23T04:56:07.000+00:00
          lat: 0.8008281904610115
          long: 6.027456183070403
        - time: 2000-01-23T04:56:07.000+00:00
          lat: 0.8008281904610115
          long: 6.027456183070403
        id: id
      properties:
        id:
          type: string
        locations:
          items:
            $ref: '#/components/schemas/LocationViewModel'
          type: array
        createdAt:
          format: date-time
          type: string
      required:
      - createdAt
      - id
      - locations
    LocationViewModel:
      example:
        time: 2000-01-23T04:56:07.000+00:00
        lat: 0.8008281904610115
        long: 6.027456183070403
      properties:
        lat:
          format: double
          type: number
        long:
          format: double
          type: number
        time:
          format: date-time
          type: string
      required:
      - lat
      - long
      - time
    SuccessViewModel:
      example:
        success: success
      properties:
        success:
          type: string
    ErrorViewModel:
      properties:
        error:
          type: string
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
