/*
 * memote
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package viewmodel

import (
	"context"
	"net/http"
	"errors"
)

// FixedRecordsApiService is a service that implents the logic for the FixedRecordsApiServicer
// This service should implement the business logic for every endpoint for the FixedRecordsApi API. 
// Include any external packages or services that will be required by this service.
type FixedRecordsApiService struct {
}

// NewFixedRecordsApiService creates a default api service
func NewFixedRecordsApiService() FixedRecordsApiServicer {
	return &FixedRecordsApiService{}
}

// GetFixedRecord - get fixed record
func (s *FixedRecordsApiService) GetFixedRecord(ctx context.Context, recordId string) (ImplResponse, error) {
	// TODO - update GetFixedRecord with the required logic for this service method.
	// Add api_fixed_records_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, FixedRecordViewModel{}) or use other options such as http.Ok ...
	//return Response(200, FixedRecordViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(400, ErrorViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(401, ErrorViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(500, ErrorViewModel{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetFixedRecord method not implemented")
}

// GetFixedRecords - get fixed records
func (s *FixedRecordsApiService) GetFixedRecords(ctx context.Context, isFixed bool) (ImplResponse, error) {
	// TODO - update GetFixedRecords with the required logic for this service method.
	// Add api_fixed_records_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []FixedRecordViewModel{}) or use other options such as http.Ok ...
	//return Response(200, []FixedRecordViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(400, ErrorViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(401, ErrorViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(500, ErrorViewModel{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetFixedRecords method not implemented")
}

// UpdateFixedRecord - update fixed record
func (s *FixedRecordsApiService) UpdateFixedRecord(ctx context.Context, recordId string, fixedRecordViewModel FixedRecordViewModel) (ImplResponse, error) {
	// TODO - update UpdateFixedRecord with the required logic for this service method.
	// Add api_fixed_records_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, FixedRecordViewModel{}) or use other options such as http.Ok ...
	//return Response(200, FixedRecordViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(400, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(400, ErrorViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(401, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(401, ErrorViewModel{}), nil

	//TODO: Uncomment the next line to return response Response(500, ErrorViewModel{}) or use other options such as http.Ok ...
	//return Response(500, ErrorViewModel{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateFixedRecord method not implemented")
}

